[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
configure = { cmd = ["cmake", "-G", "Ninja", "-S", "../mitsuba3", "-B", "build"] }
build = { cmd = ["ninja", "-C", "build"], depends-on = ["configure"]}

[dependencies]

cmake = "3.28"
cuda = "12.4"
gcc = "13.2.*"
gxx = "13.2.*"
